### PR TITLE
PPA, Updated Readme, Sound

### PR DESCRIPTION
**Pull request by archisman-panigrahi**
I have slightly modified the install scripts, and added the `install-sound` to the `postinst` script to enable sound.

I also changed architecture: `any --> amd64` so that users won't be able to install (and then complain that it doesn't work) it in a `x86` or `armhf` computer.

In future, we can build armhf binaries following [this method](https://github.com/aramg/droidcam/issues/6#issuecomment-657477309), and put it in another .zip file to build armhf .deb packages, using [this](https://github.com/paolorotolo/droidcam/blob/master/debian/rules#L35) strategy.
The user [will have to](https://github.com/aramg/droidcam/issues/60#issuecomment-633609159) run the command `pacmd load-module module-alsa-source device=hw:Loopback,1,0 source_properties=device.description=droidcam_audio` to enable sound after running droidcam, but we can later automate that in the .deb package with a script like [this](https://github.com/aramg/droidcam/issues/60#issuecomment-640776707).
I have also updated the README (fixed broken image link, edited link to PPA).

And finally, now there's a [Launchpad PPA](https://launchpad.net/~apandada1/+archive/ubuntu/droidcam) based on this repository. It will be be very easy to update the package in PPA in future, only the bundled .zip file and the `debian/changelog` has to be updated.

I have tested that it works, I will do more testing in another computer. Meanwhile, it would be great if you can test the PPA as well. Then I will notify the author of droidcam about the PPA.

### CODE REVIEW

**Comment by alexeikh** [comment]
Cool patches, thanks!

I installed the PPA, but had to overcome an obstacle during the process. Deb package version in PPA is `1.4-0~202008130452~ubuntu20.04.1`, not `1.4-0ubuntu1`, as it was written in the `debian/changelog` file. Thus installing over version `1.4-0ubuntu0` that I had before, was considered a downgrade and I had to specify the version manually, i.e. `apt install droidcam=1.4-0~202008130452~ubuntu20.04.1`. Not sure if it's a bug, maybe it's just how PPA works.

Tried to use Droidcam with MS Teams for Linux Preview version 1.3.00.16851. Video works. Audio device is found as a microphone, but I could not hear sound on the test "echo" call. Alsamixer, on the contrary, shows that "Loopback" device has only "Playback" volume, but no "Capture" volume.

**Comment by alexeikh** [comment]
After the merging I found that the pull request adds `debian/files` file to the repository. Is it so that the mentioned file is generated (see https://www.debian.org/doc/debian-policy/ch-source.html#generated-files-list-debian-files ) and thus should not be added to the repo, but should be added to `.gitignore` instead?

**Comment by archisman-panigrahi** [comment]
**Sound**: I have not tested sound myself as phone microphone stopped functioning recently (I only checked that there is a new sound input device, so I thought it would work), I will have to get one of my parents' phones to test.

**Versioning**: There are two ways to generate a ppa package in Launchpad.
1. Generate the debian source package on your computer (`debuild -S`) and upload it to Launchpad. Launchpad PPA package will have the exactly same version number as in the `changelog` file. The maintainer of the ppa will have to open Launchpad and manually generate packages for individual versions of Ubuntu (using the copy packages feature). **--->** Takes more time.

2. Make necessary changes in your computer and [git push the same code to Launchpad](https://code.launchpad.net/~apandada1/+git/droidcam). Launchpad will [build](https://code.launchpad.net/~apandada1/+recipe/droidcam-daily) the package for you and automatically generate .deb packages for all versions of Ubuntu in the specified PPA. However, the version number will be, first part of version number in `changelog` (here 1.4-0) + year(2020) + month(08) + day (13) + time in some time zone (0452).
 **--->** I am using this method to make things easier for me. This method can be made even simpler, when Launchpad will automatically import code from GitHub and build automatically if there is a new commit.

You will still get automatic updates from the PPA once you remove the `1.4-0ubuntu1` version from your computer. One workaround would be to use version numbers like `1.4.1` and so on in the `changelog` file (and remove the trailing `ubuntuX` altogether), but I did not do that as I was testing to check if the package works.

**gitignore** Yes, `debian/files` was added to the repository by mistake when I ran `debuild -S` to test whether the debian source builds correctly. It should be added to `.gitignore`. Please do that.

**A possible bug** I saw that you are using Ubuntu 20.04, which probably uses Kernel 5.4. I encountered a [bug](https://github.com/aramg/droidcam/issues/89) with Kernel 5.4 in Linux Mint 19.3 (based on Ubuntu 18.04). With this kernel, I cannot execute `./install` in the .zip file (from the [releases](https://github.com/aramg/droidcam/releases) page), and consequently the .deb package fails to install. Is this bug absent in your system?

**Comment by archisman-panigrahi** [comment]
Please enable `issues` in the settings so that we can track them one by one.

**Comment by alexeikh** [comment]
> Sound

OK.

> Versioning

OK. Thanks for the explanation. :)

> .gitignore

Added

> I saw that you are using Ubuntu 20.04, which probably uses Kernel 5.4

Yes, Ubuntu 20.04 uses Kernel 5.4 by default, but on my system I use Kernel 5.7 from https://liquorix.net/

> Is this bug absent in your system?

Yes, absent. When I still used Kernel 5.4, I didn't experience that bug either, IIRC.

However, when I started using Kernel 5.7, I had compilation issue when compiling the usual `v4l2loopback` driver, not `v4l2loopback-dc`. I solved the issue by upgrading packages `v4l2loopback-dkms` and `v4l2loopback-utils` from version `0.12.3-1` to `0.12.5-1`, taken from the next (not yet released) version of Ubuntu.

> Please enable issues in the settings so that we can track them one by one.

Enabled

**Comment by archisman-panigrahi** [comment]
Have a look at the latest comments in issue 49 of aramg/droidcam. The developer of Droidcam is against 3rd party redistribution.

**Comment by ghost** [comment]
Hello

Droidcam works fine in a 18.04 Ubuntu installation, connecting the phone and the computer to the same WIFI network.
The speakers of the computer along with the mic of the phone and the camera of the phone work in case I do any videoconference. I guess that is what droidcam is used for.

Nonetheless I would like to get the following working:

1. the computer's audio gets streamed to the phone by WIFI
2.  a bluetooth headset is connected to the phone and both the headset's microphone and the speakers transmit the computer's sound.

When I tried the following it didn't work: I connected droidcam and I played youtube videos at the same time and then the sound did not reach the phone, it stayed at the computer. Moreover, in case I connected a bluetooth headset to the phone, the mic of the headset kept playing no role at all. The only mic that worked was the phone's mic.

Does anyone know how to do this?

Thanks in advance

**Comment by archisman-panigrahi** [comment]
We are not the developers of Droidcam. We tried to package Droidcam so that it can be installed easily, but unfortunately, the developer does not want 3rd party distribution of the software (because that would increase support requests in case the packaging is faulty). 

Droidcam is meant for using the phone mic and webcam with computer, so feature 1. does not really apply to Droidcam.
Feature 2. is interesting. Kindly open an issue at the repository of Droidcam, https://github.com/aramg/droidcam/ to request this feature (but don't mention this repo, or the PPA to the developer).

**Pull request merged**
